<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE root [
		<!ELEMENT root (seleccion|aspirantes|otrosCostos|personalBase|exportables|nomina|actualizardp|distribucion|adminactualizardp|mc)*>
		<!ELEMENT seleccion (query)*>
		<!ELEMENT aspirantes (query)*>
		<!ELEMENT otrosCostos (query)*>
		<!ELEMENT personalBase (query)*>
		<!ELEMENT exportables (query)*>
		<!ELEMENT nomina (query)*>
		<!ELEMENT actualizardp (query)*>
		<!ELEMENT distribucion (query)*>
		<!ELEMENT adminactualizardp (query)*>
		<!ELEMENT mc (query)*>
		<!ELEMENT query (#PCDATA)>
		<!ATTLIST query id ID #REQUIRED>
	]>

<root>
	<seleccion>
		<query id="getDataSeleccionDetalle">
			<![CDATA[
				SELECT radicado,
					 radicado_meucci,
					 pcrc,
					 asesores_requeridos,
					 asesores_reemplazo,
					 asesores_crecimiento,
					 perfil,
					 disponibilidad_min,
					 vigencia_disp,
					 duracion_jornada,
					 duracion_contrato,
					 fecha_formacion,
					 fecha_ojt,
					 fecha_conex,
					 tipo_solicitud,
					 analista,
					 estado,
					 fecha_carga,
					 CONCAT_WS(" ", "CREACIÓN:", observacion, IFNULL(obs,'')) AS observacion
				FROM(
					SELECT CONCAT((SUBSTRING(REPLACE(ds.fecha_carga, '-', ''), 1,8)), ds.id_dp_solicitudes) AS radicado,
						 ds.radicado_meucci,
						 ds.pcrc,
						 ds.asesores_requeridos,
						 ds.asesores_reemplazo,
						 ds.asesores_crecimiento,
						 ds.perfil,
						 ds.disponibilidad_min,
						 ds.vigencia_disp,
						 ds.duracion_jornada,
						 ds.duracion_contrato,
						 ds.fecha_formacion,
						 ds.fecha_ojt,
						 ds.fecha_conex,
						 ds.tipo_solicitud,
						 ds.analista,
						 ds.estado,
						 ds.fecha_carga,
						 ds.observacion
					FROM dp_solicitudes AS ds
					WHERE ds.id_dp_solicitudes = '#ID#'
				)data1 JOIN(
					SELECT
						GROUP_CONCAT(DISTINCT db.id_observacion_solicitudes, " OBSERVACION " , ": ", db.observacion, " (",
						nombre_completo, " - ",
						db.fecha_ingreso, ")", " "
						ORDER BY db.id_observacion_solicitudes ASC) AS obs
					FROM dp_observacion_solicitudes AS db,  dp_datos_generales AS dg
					WHERE dg.documento = db.documento_ingreso
					AND db.id_dp_solicitudes = '#ID#'
				)data2
			]]>
		</query>
	</seleccion>
	<otrosCostos>
		<query id="consulta_grafica_historico">
			<![CDATA[
				SELECT fecha, costo_real, costo_ppto
				FROM(
					SELECT fecha, ROUND(SUM(costo)) AS costo_real
					FROM otros_costos_real
					WHERE fecha < '#FECHA#'
					GROUP BY fecha
				)real_c JOIN(
					SELECT fecha, ROUND(SUM(costo)) AS costo_ppto
					FROM otros_costos_ppto
					WHERE fecha < '#FECHA#'
					GROUP BY fecha
				)ppto_c USING(fecha)
				GROUP BY fecha
			]]>
		</query>
		<query id="consulta_mes_proyeccion">
			SELECT fecha, costo_proyec, costo_ppto_oc
			FROM(
				SELECT fecha, ROUND(SUM(costo)) AS costo_proyec
				FROM otros_costos_proyeccion
				WHERE fecha = '#FECHA#'
				GROUP BY fecha
			)proyecc_c JOIN(
				SELECT fecha, ROUND(SUM(costo)) AS costo_ppto_oc
				FROM otros_costos_ppto
				WHERE fecha = '#FECHA#'
				GROUP BY fecha
			)ppto_c USING(fecha)
			GROUP BY fecha
		</query>
	</otrosCostos>
	<personalBase>
		<query id="consulta_suma_costo_personal">
			<![CDATA[
				SELECT fecha, valor_real, valor_ppto,
				YEAR(fecha) AS year1,
				MONTH(fecha) AS month1,
				valor_real *(SELECT MAX(dia)
							FROM dim_tiempo
							WHERE YEAR(fecha) = year1
							AND MONTH(fecha) = month1) AS div_dias
				FROM(
					SELECT fecha, ROUND(SUM(valor)) AS valor_real
					FROM personal_base_costo_real
					WHERE fecha < '#FECHA#'
					GROUP BY fecha
				)valor_proyecc JOIN(
					SELECT fecha, ROUND(SUM(valor)) AS valor_ppto
					FROM personal_base_costo_ppto
					WHERE fecha < '#FECHA#'
					GROUP BY fecha
				)valor_ppto USING(fecha)
				GROUP BY fecha
			]]>
		</query>
		<query id="consulta_suma_costo_personal_proyecc">
		<![CDATA[
			SELECT valor_proyecc, valor_ppto
			FROM(
				SELECT fecha, ROUND(SUM(costo)) AS valor_proyecc
				FROM personal_base_teo
				WHERE fecha >= '#MES_ACT#'
				AND fecha <= '#FECHA_MAX#'
			)valor_proyecc JOIN(
				SELECT fecha, ROUND(SUM(valor)) AS valor_ppto
				FROM personal_base_costo_ppto
				WHERE fecha >= '#MES_ACT#'
				AND fecha <= '#FECHA_MAX#'
			)valor_ppto
		]]>
		</query>
		<query id="consulta_indice_personal_base">
		<![CDATA[
			SELECT fecha, valor_real, valor_ppto, real_rf, ppto_rf,
			SUBSTRING((valor_real/real_rf) *  100, 1, 4) div_real,
			SUBSTRING((valor_ppto/ppto_rf) *  100, 1, 4) div_ppto
			FROM(
				SELECT fecha,
				SUM(valor) AS valor_real
				FROM personal_base_costo_real
				WHERE fecha < '#FECHA#'
				GROUP BY fecha
			)tabla1 JOIN(
				SELECT fecha,
				SUM(valor) AS valor_ppto
				FROM personal_base_costo_ppto
				WHERE fecha < '#FECHA#'
				GROUP BY fecha
			)tabla2 USING(fecha)
			JOIN(
				SELECT fecha,
				SUM(ing_servicio)
			  + SUM(ing_canales)
			  + SUM(ing_tel_celular)
			  + SUM(ing_tel_ldi)
			  + SUM(ing_tel_ldn)
			  + SUM(ing_tel_local)
			  + SUM(ing_tel_local_extento)
			  + SUM(ing_tel_ext)
			  + SUM(total_devoluciones)
			  + SUM(costo_pena_cuentas_cobro) AS real_rf
				FROM realrf
				WHERE fecha < '#FECHA#'
				GROUP BY fecha
			)tabla3 USING(fecha)
			JOIN(
				SELECT fecha,
				SUM(ingresos) AS ppto_rf
				FROM pptorf
				WHERE fecha < '#FECHA#'
				GROUP BY fecha
			)tabla4 USING(fecha)
		]]>
		</query>
		<query id="consulta_indice_personal_base_pro">
			SELECT ppto_rf, SUBSTRING((valor_ppto/ppto_rf) *  100, 1, 4) div_ppto
			FROM(
				SELECT fecha, SUM(valor) AS valor_ppto
				FROM personal_base_costo_ppto
				WHERE YEAR(fecha) = '#YEAR#'
				AND MONTH(fecha) = '#MONTH#'
				GROUP BY fecha
			)tabla2 JOIN(
				SELECT fecha, SUM(ingresos) AS ppto_rf
				FROM pptorf
				WHERE YEAR(fecha) = '#YEAR#'
				AND MONTH(fecha) = '#MONTH#'
				GROUP BY fecha
			)tabla4
		</query>
		<query id="consulta_porcentaje_personal_base">
			SELECT fecha, nomina, dotacion, entrenamiento, horas_extras, incapacidades, transporte, indemnizacion
			FROM(
				SELECT fecha, observacion_mo, ROUND(SUM(valor)) AS nomina
				FROM personal_base_costo_real
				WHERE observacion_mo = "Costo de Personal Base"
				GROUP BY fecha, observacion_mo
			)nomina JOIN(
				SELECT fecha, observacion_mo, ROUND(SUM(valor)) AS dotacion
				FROM personal_base_costo_real
				WHERE observacion_mo = "Dotación"
				GROUP BY fecha, observacion_mo
			)dotacion USING(fecha)
			JOIN (
				SELECT fecha, observacion_mo, ROUND(SUM(valor)) AS entrenamiento
				FROM personal_base_costo_real
				WHERE observacion_mo = "Entrenamiento Inicial"
				GROUP BY fecha, observacion_mo
			)entrenamiento USING(fecha)
			JOIN (
				SELECT fecha, observacion_mo, ROUND(SUM(valor)) AS horas_extras
				FROM personal_base_costo_real
				WHERE observacion_mo = "Horas Extras y Recargos"
				GROUP BY fecha, observacion_mo
			)horas_extras USING(fecha)
			JOIN (
				SELECT fecha, observacion_mo, ROUND(SUM(valor)) AS incapacidades
				FROM personal_base_costo_real
				WHERE observacion_mo = "Incapacidades"
				GROUP BY fecha, observacion_mo
			)incapacidades USING(fecha)
			JOIN (
				SELECT fecha, observacion_mo, ROUND(SUM(valor)) AS transporte
				FROM personal_base_costo_real
				WHERE observacion_mo = "Transporte de Personal"
				GROUP BY fecha, observacion_mo
			)transporte USING(fecha)
			JOIN (
				SELECT fecha, observacion_mo, ROUND(SUM(valor)) AS indemnizacion
				FROM personal_base_costo_real
				WHERE observacion_mo = "Indemnizaciones"
				GROUP BY fecha, observacion_mo
			)indemnizacion USING(fecha)
			GROUP BY fecha
		</query>
		<query id="consulta_total_tipo_diario">
		<![CDATA[
			SELECT tipo, ROUND(SUM(resultado)) AS resp
			FROM(
				SELECT tipo, (SUM(costo)/peso) AS resultado
				FROM(
					SELECT fecha AS fecha_pesos, tipo, id_cc AS id_pesos, SUM(costo) AS costo
						FROM personal_base_teo
						WHERE tipo in ('Salario base',
									'Auxilio transporte',
									'Entrenamiento Contratado',
									'Horas Extras y Recargos',
									'Prestaciones',
									'Seguridad social',
									'Entrenamiento inicial')
						AND fecha >= '#MES_ACT#'
					  AND fecha <= '#MAX_FECHA#'
				GROUP BY id_pesos, tipo
				)pesos JOIN(
					SELECT fecha AS fecha_analista, id_cc AS id_analista, sum(peso)/100 AS peso
					FROM pesos_analistas
					WHERE fecha >= '#MES_ACT#'
					AND fecha <= (SELECT MAX(fecha)
								  FROM personal_base_teo
								  WHERE fecha >= '#MES_ACT#'
								  AND fecha <= '#MAX_FECHA#')
					GROUP BY id_analista
				)analista
				WHERE id_pesos = id_analista
				AND fecha_pesos = fecha_analista
				GROUP BY id_pesos, tipo
			)final
			GROUP BY tipo
		]]>
		</query>
		<query id="consulta_total_tipo_mensual">
		<![CDATA[
			SELECT tipo, ROUND(SUM(costo)) AS resultado
			FROM personal_base_teo
			WHERE tipo in ('Actividades Deportivas',
						   'Centro de mensajeria',
						   'Fullfilmen',
						   'Incapacidades',
						   'Incentivos y Bonificaciones',
						   'Indemnizaciones',
						   'Medicamentos',
						   'Sena etapa lectiva',
						   'Transporte Nocturno',
						   'Dotación',
						   'Salud Ocupacional',
						   'Técnicos')
			AND fecha >= '#MES_ACT#'
			AND fecha <= '#MAX_FECHA#'
			GROUP BY tipo
		]]>
		</query>
	</personalBase>
	<exportables>
		<query id="exportable_nominaComp">
			<![CDATA[
				SELECT data1.estado,
					 data1.cedula,
					 data1.nombreColaborador,
					 data1.tipoNovedad,
					 data1.motivoNovedad,
					 data1.descripcionNovedad,
					 data1.cliente,
					 data1.ceco,
					 data1.nombreCeco,
					 data1.director,
					 data1.gerente,
					 data1.horaInicio,
					 data1.horaFin,
					 data1.fechaNovedad,
					 data1.totalTiempo,
					 data1.tiempoDiurno,
					 data1.tiempoNocturno,
					 data1.cedulaResponsableIng,
					 data1.nombreResponsableIng,
					 data1.fecha_ingreso,
					 data2.cedulaAprobador,
					 data2.nombreAprobador,
					 data2.fechaAprobacion,
					 data1.consecutivo,
					 data1.observacion
				FROM(
				SELECT est.nombre AS estado,
					   nn.id_nov_novedad AS idNov,
					   nn.documento_ingreso AS cedula,
					   dg.nombre_completo AS nombreColaborador,
					   nt.nombre AS tipoNovedad,
					   nm.nombre AS motivoNovedad,
						nd.nombre AS descripcionNovedad,
						dc.cliente AS cliente,
						SUBSTR(dp.pcrc, 1, 6) AS ceco,
						ceco.centros_costos AS nombreCeco,
						ceco.director_programa AS director,
						ceco.gerente_cuenta AS gerente,
						TIME(nn.hora_inicio_novedad) AS horaInicio,
						TIME(nn.hora_fin_novedad) AS horaFin,
						DATE(nn.hora_inicio_novedad) AS fechaNovedad,

						SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60) AS totalTiempo,

						IF(SUBSTR(nn.hora_fin_novedad, 11) < TIME('21:00:00'), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60), TIME('0:00:00')) AS tiempoDiurno,
						IF(SUBSTR(nn.hora_fin_novedad, 11) > TIME('21:00:00'), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60), TIME('0:00:00')) AS tiempoNocturno,

						nn.documento_ingreso AS cedulaResponsableIng,
						dg.nombre_completo AS nombreResponsableIng,
						nn.fecha_ingreso AS fecha_ingreso,
						nn.id_nov_novedad AS consecutivo,
						nn.observacion
				FROM nov_novedad AS nn, nov_descripcion_novedad AS nd, nov_motivo_novedad AS nm, nov_tipo_novedad AS nt, dp_distribucion_personal AS dp, dp_datos_generales AS dg, dp_clientes AS dc,  dp_centros_costos AS ceco, nov_estado_novedad AS est
				WHERE nn.documento_ingreso = dg.documento
				AND dg.documento = dp.documento
				AND nn.id_nov_descripcion_novedad = nd.id_nov_descripcion_novedad
				AND nd.id_nov_motivo_novedad = nm.id_nov_motivo_novedad
				AND SUBSTR(dp.pcrc,1 ,3) = dc.id_dp_clientes
				AND ceco.id_dp_centros_costos = SUBSTR(dp.pcrc, 1, 6)
				AND nd.id_nov_motivo_novedad = nm.id_nov_motivo_novedad
				AND nm.id_nov_tipo_novedad = nt.id_nov_tipo_novedad
				AND DATE(nn.hora_inicio_novedad) >= '#FECHA_INICIO#'
				AND DATE(nn.hora_inicio_novedad) <= '#FECHA_FIN#'
				AND nn.id_nov_estado_novedad = est.id_nov_estado_novedad
				)data1 JOIN(
				SELECT np.id_nov_novedad AS idAprob,
						np.documento_aprobador AS cedulaAprobador,
						dg.nombre_completo AS nombreAprobador,
						np.fecha AS fechaAprobacion
				FROM nov_proceso_novedad AS np, dp_datos_generales AS dg, nov_novedad AS nn
				WHERE np.documento_aprobador = dg.documento
				AND np.id_nov_novedad = nn.id_nov_novedad
				AND nn.id_nov_estado_novedad = np.id_nov_estado_novedad
				)data2
				WHERE idAprob = idNov
				GROUP BY consecutivo
			]]>
		</query>
		<query id="exportable_nomina">
			<![CDATA[
				SELECT estado, cedula, nombreColaborador, tipoNovedad, motivoNovedad, descripcionNovedad,  ceco, nombreCeco, horaInicio, horaFin, fechaNovedad, totalTiempo, tiempoDiurno, tiempoNocturno, cedulaResponsableIng, nombreResponsableIng, fecha_ingreso, cedulaAprobador, nombreAprobador, fechaAprobacion, consecutivo, observacion
				FROM(
					SELECT est.nombre AS estado,
					nn.id_nov_novedad AS idNov,
					nn.documento_ingreso AS cedula,
					dg.nombre_completo AS nombreColaborador,

					nt.nombre AS tipoNovedad,
					nm.nombre AS motivoNovedad,
					nd.nombre AS descripcionNovedad,

					SUBSTR(dp.pcrc, 1, 6) AS ceco,
					ceco.centros_costos AS nombreCeco,
					TIME(nn.hora_inicio_novedad) AS horaInicio,
					TIME(nn.hora_fin_novedad) AS horaFin,
					DATE(nn.hora_inicio_novedad) AS fechaNovedad,
					SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60) AS totalTiempo,

					IF(TIME(nn.hora_fin_novedad) < TIME('21:00:00'), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60), TIME('0:00:00')) AS tiempoDiurno,
					IF(TIME(nn.hora_fin_novedad) > TIME('21:00:00'), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60), TIME('0:00:00')) AS tiempoNocturno,

					nn.documento_ingreso AS cedulaResponsableIng,
					dg.nombre_completo AS nombreResponsableIng,
					nn.fecha_ingreso,
					nn.id_nov_novedad AS consecutivo,
					nn.observacion AS observacion
					FROM nov_novedad AS nn, nov_descripcion_novedad AS nd, nov_motivo_novedad AS nm, nov_tipo_novedad AS nt, dp_distribucion_personal AS dp, dp_datos_generales AS dg, dp_clientes AS dc,  dp_centros_costos AS ceco, nov_estado_novedad AS est
					WHERE nn.documento_ingreso = dg.documento
					AND dg.documento = dp.documento
					AND nn.id_nov_descripcion_novedad = nd.id_nov_descripcion_novedad
					AND nd.id_nov_motivo_novedad = nm.id_nov_motivo_novedad
					AND ceco.id_dp_centros_costos = SUBSTR(dp.pcrc, 1, 6)
					AND nd.id_nov_motivo_novedad = nm.id_nov_motivo_novedad
					AND nm.id_nov_tipo_novedad = nt.id_nov_tipo_novedad
					AND DATE(nn.hora_inicio_novedad) >= '#FECHA_INICIO#'
					AND DATE(nn.hora_inicio_novedad) <= '#FECHA_FIN#'
				   	AND nn.id_nov_estado_novedad = est.id_nov_estado_novedad
				   	AND nt.id_nov_tipo_novedad = 2
				)data1 JOIN(
					SELECT nn.id_nov_estado_novedad,
					np.id_nov_novedad AS idAprob,
					np.documento_aprobador AS cedulaAprobador, dg.nombre_completo AS nombreAprobador,
					np.fecha AS fechaAprobacion
					FROM nov_proceso_novedad AS np, dp_datos_generales AS dg, nov_novedad AS nn
					WHERE np.documento_aprobador = dg.documento
					AND np.id_nov_novedad = nn.id_nov_novedad
					AND nn.id_nov_estado_novedad = np.id_nov_estado_novedad
				)data2
				WHERE idAprob = idNov
				GROUP BY consecutivo
			]]>
		</query>
		<query id="exportable_turnos1">
			<![CDATA[
				SELECT id1, fecha, documento, pcrc, cliente, tipoEvento, inicioTurno, finTurno, inicioEvento, finEvento, SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , inicioEvento, finEvento))*60) AS totalTiempo
				FROM(
					SELECT tt.id_tur_turnos_usuarios AS id1, tt.fecha_creacion AS fecha,  tt.documento AS documento, tt.pcrc AS pcrc, dc.cliente AS cliente, tt.inicio AS inicioTurno, tt.fin AS finTurno
					FROM tur_turnos_usuarios AS tt, dp_clientes AS dc
					WHERE SUBSTR(tt.pcrc, 1, 3) = dc.id_dp_clientes
					AND SUBSTR(tt.inicio, 1, 10) >= '#FECHA_INICIO#'
					AND SUBSTR(tt.inicio, 1, 10) <= '#FECHA_FIN#'

				)data1 JOIN(
					SELECT te.id_tur_turnos_usuarios AS id2,
					te.inicio AS inicioEvento,
					te.fin AS finEvento,
					tp.nombre AS tipoEvento

					FROM tur_eventos_turnos AS te, tur_tipo_turnos AS tp
					WHERE te.num_tipo_turno = tp.num_tipo_turno
				)eventos
				WHERE id1= id2
				ORDER BY id1 ASC
			]]>
		</query>
		<query id="exportable_turnos2">
			<![CDATA[
				SELECT
					data1.id,
					data1.cedula,
					data1.fecha,
					SEC_TO_TIME(SUM(TIME_TO_SEC(data1.even1) + TIME_TO_SEC(data1.evento1) +
										 TIME_TO_SEC(data1.diu1))) AS diurnoConex,
					SEC_TO_TIME(SUM(TIME_TO_SEC(data1.even11) + TIME_TO_SEC(data1.evento11) +
									    TIME_TO_SEC(data1.noc1))) AS nocturnoConex,
					SEC_TO_TIME(SUM(TIME_TO_SEC(data1.even1) + TIME_TO_SEC(data1.even11) +
										 TIME_TO_SEC(data1.evento1) + TIME_TO_SEC(data1.diu1) +
										 TIME_TO_SEC(data1.evento11) + TIME_TO_SEC(data1.noc1))) AS total,

					SEC_TO_TIME(SUM(TIME_TO_SEC(data2.even2) + TIME_TO_SEC(data2.evento2) +
										 TIME_TO_SEC(data2.diu2))) AS diurnoConex1,
					SEC_TO_TIME(SUM(TIME_TO_SEC(data2.even22) + TIME_TO_SEC(data2.evento22) +
									    TIME_TO_SEC(data2.noc2))) AS nocturnoConex1,
					SEC_TO_TIME(SUM(TIME_TO_SEC(data2.even2) + TIME_TO_SEC(data2.even22) +
										 TIME_TO_SEC(data2.evento2) + TIME_TO_SEC(data2.diu2) +
										 TIME_TO_SEC(data2.evento22) + TIME_TO_SEC(data2.noc2))) AS total1,

					SEC_TO_TIME(SUM(TIME_TO_SEC(data3.even3) + TIME_TO_SEC(data3.evento3) +
										 TIME_TO_SEC(data3.diu3))) AS diurnoConex2,
					SEC_TO_TIME(SUM(TIME_TO_SEC(data3.even33) + TIME_TO_SEC(data3.evento33) +
									    TIME_TO_SEC(data3.noc3))) AS nocturnoConex2,
					SEC_TO_TIME(SUM(TIME_TO_SEC(data3.even3) + TIME_TO_SEC(data3.even33) +
										 TIME_TO_SEC(data3.evento3) + TIME_TO_SEC(data3.diu3) +
										 TIME_TO_SEC(data3.evento33) + TIME_TO_SEC(data3.noc3))) AS total2
					FROM(
						SELECT
							te.id_tur_turnos_usuarios AS id,
							tt.documento AS cedula,
							SUBSTR(tt.inicio, 1, 10) AS fecha,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 1,
									IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('06:00:00')) AND (TIME(SUBSTR(te.fin, 11)) > TIME('06:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME(SUBSTR(te.inicio, 11)), TIME('06:00:00')))*60), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS even1,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 1,
									IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('21:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME(SUBSTR(te.inicio, 11)), TIME('21:00:00')))*60), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS evento1,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 1,
									IF((TIME(SUBSTR(te.inicio, 11)) >= TIME('06:00:00')) AND (TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')),
										IF((TIME(SUBSTR(te.fin, 11	)) <= TIME('21:00:00')) AND (TIME(SUBSTR(te.fin, 11)) != TIME('00:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , te.inicio, te.fin))*60),
												TIME('00:00:00')
										), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS diu1,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 1,
									IF((TIME(SUBSTR(te.inicio, 11)) < TIME('06:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('06:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME('06:00:00'), TIME(SUBSTR(te.fin, 11))))*60), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS even11,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 1,
									IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('21:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME('21:00:00'), TIME(SUBSTR(te.fin, 11))))*60), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS evento11,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 1,
									IF((TIME(SUBSTR(te.inicio, 11)) >= TIME('21:00:00')) OR (TIME(SUBSTR(te.inicio, 11)) <= TIME('06:00:00') OR (TIME(SUBSTR(te.fin, 11)) = TIME('00:00:00'))),
										IF((TIME(SUBSTR(te.fin, 11	)) <= TIME('06:00:00')), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , te.inicio, te.fin))*60),
												TIME('00:00:00')
										), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS noc1

						FROM tur_eventos_turnos AS te, tur_turnos_usuarios AS tt
						WHERE SUBSTR(tt.inicio, 1, 10) >= '#FECHA_INICIO#'
						AND SUBSTR(tt.inicio, 1, 10) <= '#FECHA_FIN#'
						AND tt.id_tur_turnos_usuarios = te.id_tur_turnos_usuarios

						GROUP BY id
					)data1 JOIN(
					SELECT
						te.id_tur_turnos_usuarios AS id1,

						SEC_TO_TIME(SUM(TIME_TO_SEC(
						IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('06:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('06:00:00')),
							SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME(SUBSTR(te.inicio, 11)), TIME('06:00:00')))*60), TIME('00:00:00')
						)))) AS even2,

						SEC_TO_TIME(SUM(TIME_TO_SEC(
						IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('21:00:00')),
							SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME(SUBSTR(te.inicio, 11)), TIME('21:00:00')))*60), TIME('00:00:00')
						)))) AS evento2,

						SEC_TO_TIME(SUM(TIME_TO_SEC(
						IF((TIME(SUBSTR(te.inicio, 11)) >= TIME('06:00:00')) AND (TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')),
							IF((TIME(SUBSTR(te.fin, 11	)) <= TIME('21:00:00')), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , te.inicio, te.fin))*60),
									TIME('00:00:00')
							), TIME('00:00:00')
						)))) AS diu2,

						SEC_TO_TIME(SUM(TIME_TO_SEC(
						IF((TIME(SUBSTR(te.inicio, 11)) < TIME('06:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('06:00:00')),
							SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME('06:00:00'), TIME(SUBSTR(te.fin, 11))))*60), TIME('00:00:00')
						)))) AS even22,

						SEC_TO_TIME(SUM(TIME_TO_SEC(
						IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('21:00:00')),
							SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME('21:00:00'), TIME(SUBSTR(te.fin, 11))))*60), TIME('00:00:00')
						)))) AS evento22,

						SEC_TO_TIME(SUM(TIME_TO_SEC(
						IF((TIME(SUBSTR(te.inicio, 11)) >= TIME('21:00:00')) OR (TIME(SUBSTR(te.inicio, 11)) <= TIME('06:00:00') OR (TIME(SUBSTR(te.fin, 11)) = TIME('00:00:00'))),
							IF((TIME(SUBSTR(te.fin, 11	)) <= TIME('06:00:00')), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , te.inicio, te.fin))*60),
									TIME('00:00:00')
							), TIME('00:00:00')
						)))) AS noc2

					FROM tur_eventos_turnos AS te
					WHERE te.num_tipo_turno NOT IN(2, 3)
					GROUP BY id1
					)data2 JOIN(
						SELECT
							te.id_tur_turnos_usuarios AS id2,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 2,
									IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('06:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('06:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME(SUBSTR(te.inicio, 11)), TIME('06:00:00')))*60), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							)))AS even3,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 2,
									IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('21:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME(SUBSTR(te.inicio, 11)), TIME('21:00:00')))*60), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS evento3,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 2,
									IF((TIME(SUBSTR(te.inicio, 11)) >= TIME('06:00:00')) AND (TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')),
										IF((TIME(SUBSTR(te.fin, 11	)) <= TIME('21:00:00')), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , te.inicio, te.fin))*60),
												TIME('00:00:00')
										), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS diu3,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 2,
									IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('06:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('06:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME('06:00:00'), TIME(SUBSTR(te.fin, 11))))*60), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS even33,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 2,
									IF((TIME(SUBSTR(te.inicio, 11)) <= TIME('21:00:00')) AND (TIME(SUBSTR(te.fin, 11)) >= TIME('21:00:00')),
										SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , TIME('21:00:00'), TIME(SUBSTR(te.fin, 11))))*60), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS evento33,

							SEC_TO_TIME(SUM(TIME_TO_SEC(
								IF(te.num_tipo_turno = 2,
									IF((TIME(SUBSTR(te.inicio, 11)) >= TIME('21:00:00')) OR (TIME(SUBSTR(te.inicio, 11)) <= TIME('06:00:00') OR (TIME(SUBSTR(te.fin, 11)) = TIME('00:00:00'))),
										IF((TIME(SUBSTR(te.fin, 11	)) <= TIME('06:00:00')) OR TIME(SUBSTR(te.fin, 11)) >= TIME('06:00:00'), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , te.inicio, te.fin))*60),
												TIME('00:00:00')
										), TIME('00:00:00')
									)
								, TIME('00:00:00'))
							))) AS noc3

						FROM tur_eventos_turnos AS te
						GROUP BY id2
					)data3
				WHERE id = id1
				AND id = id2
				GROUP BY id
				ORDER BY id ASC
			]]>
		</query>
		<query id="exportable_sap">
			<![CDATA[
				SELECT cedula,
						'DESCONEXIONES AUTORIZADAS' AS Nov,
						TIME('0:00:00') AS '-',
						TIME('0:00:00') AS '- ',
						TIME(SUM(ROUND(TIME_TO_SEC(diurno)/(60*60),3)) + SUM(ROUND(TIME_TO_SEC(nocturno)/(60*60),3))) AS total,
						TIME(SUM(ROUND(TIME_TO_SEC(diurno)/(60*60),3))) AS diurno,
						TIME(SUM(ROUND(TIME_TO_SEC(nocturno)/(60*60),3))) AS nocturno,
						fechas,
						costo
				FROM(
					SELECT nn.documento_ingreso AS cedula,

					SEC_TO_TIME(TIME_TO_SEC(
					IF(TIME('06:00:00') <= TIME(SUBSTR(nn.hora_inicio_novedad, 11)) AND TIME('21:00:00') > TIME(SUBSTR(nn.hora_fin_novedad, 11)), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60), TIME('0:00:00')))) AS diurno,

					SEC_TO_TIME(TIME_TO_SEC(
					IF(TIME('06:00:00') <= TIME(SUBSTR(nn.hora_inicio_novedad, 11)) AND TIME('21:00:00') > TIME(SUBSTR(nn.hora_fin_novedad, 11)), TIME('0:00:00'), SEC_TO_TIME((TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60)))) AS nocturno,

					REPLACE(SUBSTR(nn.hora_inicio_novedad, 1, 10), "-", ".") AS fechas,
					SUBSTR(IF(LENGTH(dp.pcrc) > 1, CONCAT(5718, dp.pcrc), IF(LENGTH(dp.ceco_op)>1, CONCAT(5718, dp.ceco_op), dp.ceco_area)), 1, 10) AS costo

					FROM nov_novedad AS nn, nov_proceso_novedad AS np, dp_distribucion_personal AS dp, nov_descripcion_novedad AS nd, nov_motivo_novedad AS nm
					WHERE nn.id_nov_novedad = np.id_nov_novedad
					AND nn.id_nov_estado_novedad IN(3, 6)
					AND nn.documento_ingreso = dp.documento

					AND nn.id_nov_descripcion_novedad = nd.id_nov_descripcion_novedad
					AND nd.id_nov_motivo_novedad = nm.id_nov_motivo_novedad
					AND nm.id_nov_tipo_novedad	 = 2

					AND SUBSTR(nn.hora_inicio_novedad, 1, 10) >=  '#FECHA_INICIO#'
					AND SUBSTR(nn.hora_inicio_novedad, 1, 10) <=  '#FECHA_FIN#'
					GROUP BY cedula, fechas, nn.hora_inicio_novedad
				)data1
				GROUP BY cedula, fechas
				ORDER BY cedula DESC
			]]>
		</query>
		<query id="exportable_adh">
			<![CDATA[
				SELECT data1.inicio,
				    	data1.cedula,
				    	data1.nombre,
				    	data1.cliente,
				    	data1.pcrc,
				    	data1.inicioTurno,
				    	data1.finTurno,
				    	data1.jornadaProgramada,
				    	data2.horasTeoricas,
						data3.horasConex,
						IFNULL(data4.afectanAdh, 0) AS afectan,
						IFNULL(data5.noAfectanAdh, 0) AS noAfectan,
				    	data6.inicioConex,
				    	data7.finConex,
				    	(data3.horasConex + IFNULL(data4.afectanAdh, 0)) AS total
				FROM(
					SELECT tt.id_tur_turnos_usuarios AS id,
					       tt.inicio, tt.documento,
					       CONCAT_WS(" ",dg.primer_nombre, dg.segundo_nombre, dg.primer_apellido, dg.segundo_apellido) AS nombre,
					       tt.pcrc AS pcrc,
					       dc.cliente,
					       tt.inicio AS inicioTurno,
					       tt.fin AS finTurno,
						   ROUND(TIME_TO_SEC(SEC_TO_TIME(SUM(TIMESTAMPDIFF(MINUTE , tt.inicio, tt.fin))*60))/(60*60), 3) AS jornadaProgramada
					FROM tur_turnos_usuarios AS tt
					JOIN dp_datos_generales AS dg
					JOIN dp_clientes AS dc
					WHERE tt.documento = dg.documento
					AND SUBSTR(tt.pcrc, 1, 3) = dc.id_dp_clientes
					AND SUBSTR(tt.inicio, 1, 10) >= '#FECHA_INICIO#'
					AND SUBSTR(tt.inicio, 1, 10) <= '#FECHA_FIN#'
					GROUP BY id
				)data1
				JOIN(
					SELECT tt.id_tur_turnos_usuarios AS id1,
					       tt.documento AS cc,
					       ROUND(TIME_TO_SEC(SEC_TO_TIME(SUM(TIMESTAMPDIFF(MINUTE , te.inicio, te.fin))*60))/(60*60), 3) AS HorasTeoricas
					FROM tur_turnos_usuarios AS tt
					JOIN tur_eventos_turnos AS te ON tt.id_tur_turnos_usuarios = te.id_tur_turnos_usuarios
					WHERE te.num_tipo_turno NOT IN(2,3,17)
					GROUP BY tt.id_tur_turnos_usuarios,tt.documento
				)data2 ON data2.id1 = data1.id
				JOIN(
				SELECT tt.id_tur_turnos_usuarios AS id2,
					   tt.documento AS cc,
				       SUBSTR(tt.inicio, 1,10) AS fecha,
				       ROUND(TIME_TO_SEC(SEC_TO_TIME(SUM(TIMESTAMPDIFF(MINUTE , te.inicio, te.fin))*60))/(60*60), 3) AS horasConex
					FROM tur_turnos_usuarios AS tt
					JOIN tur_eventos_turnos AS te ON  tt.id_tur_turnos_usuarios = te.id_tur_turnos_usuarios
					WHERE te.num_tipo_turno = 1
					GROUP BY tt.id_tur_turnos_usuarios,tt.documento
				)data3 ON data3.id2 = data2.id1
				LEFT JOIN(
					SELECT nn.documento_ingreso AS cc1,
						SUBSTR(nn.hora_inicio_novedad, 1,10) AS fechaIni,
						ROUND(TIME_TO_SEC(SEC_TO_TIME(SUM(TIMESTAMPDIFF(MINUTE , nn.hora_inicio_novedad, nn.hora_fin_novedad))*60))/(60*60), 3) AS afectanAdh
					FROM nov_novedad AS nn